### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-lambda-functions#1]
in 
_"As you can see, extra spaces won't break our fucntion, but missing a space after punctuation will. Perhaps this is a rare enough event that we don't worry further, but exceptions are always something to consider when writing functions."_

"fucntion" should be "function"

**Comment by sumedh10** [comment]
Thanks, fixed here a5fe14d044749abd4bbcc09c1c2daf485f364205
