### ISSUE TITLE
Floor division issue

### ISSUE THREAD

**Issue by dquinnjr** [learn-co-curriculum/dsc-lambda-functions#2]
`# Generalize the pattern: every other
for i in range(10):
    print('i: {}, i//2: {}'.format(i, i//3))`

I believe the formula uses i//3 but prints i//2

**Comment by Cheffrey2000** [comment]
This issue has been fixed with the following commit: [a54a298](https://github.com/learn-co-curriculum/dsc-lambda-functions/commit/a54a298c481e863edc7de262b73c8e62d5b0f56c)
