### ISSUE TITLE
floor division typo

### ISSUE THREAD

**Issue by marvelje** [learn-co-curriculum/dsc-lambda-functions#3]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4257/assignments/140984?module_item_id=294062

## What should be changed?

There is a typo in the print statement illustrating the floor division operator. I was confused why 2//2 = 0 before I realized the calculation in the .format (i//3) did not equal the text, which reads i//2.

# Generalize the pattern: every other
for i in range(10):
    print('i: {}, i//2: {}'.format(i, i//3))

## Additional context

> Add any other context about the problem here.

**Comment by Cheffrey2000** [comment]
This issue has been fixed with the following commit: [a54a298](https://github.com/learn-co-curriculum/dsc-lambda-functions/commit/a54a298c481e863edc7de262b73c8e62d5b0f56c)
